name: GitHub Actions Demo
run-name: ${{ github.actor }} is running addressbook tests
on: workflow_dispatch
jobs:
  Run-Squish-Addressbook-Tests:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Run addressbook tests
        run: python run_suites_script.py
        shell: cmd
         
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: 'C:/Report/results/final/*.xml'
          summary: true
          detailed_summary : true
          include_passed : true
                
      - name: Test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: Test reports
          path: |
            C:\Report\results\
              
