name: GitHub Actions Demo
run-name: ${{ github.actor }} is running addressbook tests
on: workflow_dispatch
jobs:
  Run-Squish-Addressbook-Tests:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Run addressbook tests
        run: C:\Users\john_\Squish_for_Qt_6.7.2\bin\squishrunner.exe --testsuite suite_ADF_test --local --exitCodeOnFail 13 --reportgen junit,reports/xml/junit_report.xml --reportgen html,reports/web_report
        shell: cmd
         
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/reports/xml/*.xml'
          
      - name: Test results
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: My Artifacts
          path: |
            ${{ github.workspace }}/reports/
