name: GitHub Actions Demo
run-name: ${{ github.actor }} is running addressbook tests
on: workflow_dispatch
jobs:
  Run-Squish-Addressbook-Tests:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Run addressbook tests
        run: C:\Squish_for_Qt_6.7.2\bin\squishrunner.exe --testsuite suite_captures --testcase tst_captures_tests_in_BDD --local --exitCodeOnFail 13 --reportgen junit,reports/xml/junit_report.xml --reportgen html,reports/web_report
        shell: cmd
         
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/reports/xml/*.xml'
    
      - name: Test results
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: Test reports
          path: |
            ${{ github.workspace }}/reports/

  job-1:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: self-hosted
      steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Setup Pages
            uses: actions/configure-pages@v2
          - name: Upload artifact
            uses: actions/upload-pages-artifact@v1
            with:
              # Upload entire repository
              path: |
                ${{ github.workspace }}/reports/
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v1
