name: GitHub Actions Demo
run-name: ${{ github.actor }} is running addressbook tests
on: workflow_dispatch
jobs:
  Run-Squish-Addressbook-Tests:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Run addressbook tests
        run: python run_suites_script.py
        shell: cmd
         
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: '${{ github.workspace }}/reports/web_report/index.html'
    
      - name: Test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: Test reports
          path: |
            ${{ github.workspace }}/reports/
              
