name: GitHub Actions Demo
run-name: ${{ github.actor }} is running addressbook tests
on: workflow_dispatch
jobs:
  Run-Squish-Addressbook-Tests:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Run addressbook tests
        run: python run_suites_script.py
        shell: cmd
         
      - name: Publish new framework test results
        uses: EnricoMi/publish-unit-test-result-action/windows/bash@v2
        if: always()
        with:
          files: |
            'C:/Report/results/final/*.xml'
    
      - name: Test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: Test reports
          path: |
            C:\Report\results\
              
