# This is a basic workflow to help you get started with Actions

name: GitHub Actions Demo
run-name: ${{ github.actor }} is running addressbook tests
# Controls when the workflow will run
on: workflow_dispatch
  # Triggers the workflow on push or pull request events but only for the "main" branch


  # Allows you to run this workflow manually from the Actions tab
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Run-Squish-Addressbook-Tests:
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
      - uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: Run addressbook tests
        run: C:\Users\john_\Squish_for_Qt_6.7.2\bin\squishrunner.exe --testsuite suite_ADF_test --local --exitCodeOnFail 13 --reportgen junit,reports/xml/junit_report.xml --reportgen html,reports/web_report
        shell: cmd
        
      # Runs a set of commands using the runners shell
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/reports/xml/*.xml'
          
      - name: Upload Artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: My Artifacts
          path: |
            ${{ github.workspace }}/reports/
